name: GitHub Actions + Oras 
on: [push]
jobs:
  Use-Oras:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: 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
    steps:
      - name: "Loging"
        run: echo $GITHUB_PAT
        run: echo $GITHUB_PAT | oras login https://ghcr.io -u MichaelKora --password-stdin
      - name: "Pushing"
        run: oras push ghcr.io/${GITHUB_OWNER}/samples/artifact:1.0 ../../conda-forge_xtensor_files/* 
      - name: "Check current status"
        run: echo "🍏 The current status is ${{ job.status }}."
