name: Create Oras event after each git push

on: [ push ]

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: conda-forge_xtensor_files

jobs:
  create_oras_push:
    runs-on: ubuntu-18.04 
    env:
      GITHUB_OWNER: ${{ github.actor }} 
    steps:
      - uses: actions/checkout@v2
      - run: wget https://github.com/oras-project/oras/releases/download/v0.12.0/oras_0.12.0_linux_arm64.tar.gz
      - run: tar -xvf oras_0.12.0_linux_arm64.tar.gz

      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: oras push ghcr.io/${ GITHUB_OWNER } ./*
      - run: echo "🍏 The current status is ${{ job.status }}."
