name: Create Oras event after each git push

on: [ push ]

permissions:
  contents: read
  pull-requests: write
  packages: write


defaults:
  run:
    working-directory: ./

jobs:
  create_oras_push:
    runs-on: ubuntu-latest 
    env:
      GITHUB_OWNER: ${{ github.actor }} 
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: my_env.yml
          micromamba-version: latest

      - run: chmod +x ./conda_index.sh

      - name: create repodata.json
        run: ./conda_index.sh
        shell: bash -l {0} 

      - run: echo ${{ secrets.GITHUB_TOKEN }} | oras login https://ghcr.io -u ${{ env.GITHUB_OWNER }} --password-stdin

      - name: upload all tar.bz2 files
        run: ./upload-files.sh ${{ env.GITHUB_OWNER }}
        shell: bash -l {0} 

#      - run: |
         #echo ${{ secrets.GITHUB_TOKEN }} | oras login https://ghcr.io -u ${{ env.GITHUB_OWNER }} --password-stdin

         #my_array=($( ls ./conda-forge_xtensor_files/*.bz2 ) )
         #for i in "${my_array[@]}"
         #do
         #oras push ghcr.io/${{ env.GITHUB_OWNER }}/samples/xtensor:1.1 ./$i:application/octet-stream
         #done

      - run: oras push ghcr.io/${{ env.GITHUB_OWNER }}/samples/xtensor:1.1 ./temp_dir/noarch/repodata.json:application/vnd.unknown.layer.v1+txt
      - run: echo "🍏 The current status is ${{ job.status }}."

