name: Create Oras event after each git push

on: [ push ]

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: conda-forge_xtensor_files

jobs:
  create_oras_push:
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: ${{ github.actor }} 
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: oras push ghcr.io/${ GITHUB_OWNER } ./*
      - run: echo "🍏 The current s    tatus is ${{ job.status }}."
